config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :interactions
  resources :legalissues
  resources :problems

   root 'home#home'

   get '/businessplan', to: 'businessplan#businessPlan'    # verb 'path', to: 'controller#action'
   get '/backendprocess', to: 'backendprocess#backendProcess'
   get '/usertype', to: 'usertype#userType'
   get '/problem', to: 'problems#index'
   get '/legalissues', to: 'legalissues#index'
   
   get '/interacttemp', to: 'interacttemp#interactTemp'
   get '/createanewrequest', to: 'createanewrequest#createANewRequest'
   
   
   get '/sptcimage', to: 'sptcimage#sptcImage'   #
   get '/ctgspimage', to: 'ctgspimage#ctgspImage' #
   get '/ctspimage', to: 'ctspimage#ctspImage' #
   get '/gctspgimage', to: 'gctspgimage#gctspgImage' #
   get '/gsptcgimage', to: 'gsptcgimage#gsptcgImage' #
   get '/gsptcimage', to: 'gsptcimage#gsptcImage' #
   get '/ilsimage', to: 'ilsimage#ilsImage'  #
   get '/sptgcimage', to: 'sptgcimage#sptgcImage' #
   get '/gctspimage', to: 'gctspimage#gctspImage' #
   get '/adminimage', to: 'adminimage#adminImage' #
   
   
   get '/sptcvwt', to: 'sptcvwt#sptcVWT' #
   get '/ctgspvwt', to: 'ctgspvwt#ctgspVWT' # 
   get '/ctspvwt', to: 'ctspvwt#ctspVWT' #
   get '/gctspgvwt', to: 'gctspgvwt#gctspgVWT' #
   get '/gsptcgvwt', to: 'gsptcgvwt#gsptcgVWT' #
   get '/gsptcvwt', to: 'gsptcvwt#gsptcVWT'
   get '/ilsvwt', to: 'ilsvwt#ilsVWT' #
   get '/sptgcvwt', to: 'sptgcvwt#sptgcVWT' # 
   get '/gctspvwt', to: 'gctspvwt#gctspVWT' #
   get '/adminvwt', to: 'adminvwt#adminVWT'  #
   
   get '/playground', to: 'playground#playGround' #
   get '/vcrtemp', to: 'vcrtemp#vCrTemp' #
   
   

end

app/models/interaction.rb
class Interaction < ActiveRecord::Base
end

app/models/legalissue.rb
class Legalissue < ActiveRecord::Base
end

app/models/problem.rb
class Problem < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/adminvwt_helper.rb
module AdminvwtHelper
end

app/helpers/ctgspvwt_helper.rb
module CtgspvwtHelper
end

app/helpers/ctspimage_helper.rb
module CtspimageHelper
end

app/helpers/ctspvwt_helper.rb
module CtspvwtHelper
end

app/helpers/gctspvwt_helper.rb
module GctspvwtHelper
end

app/helpers/gsptcgvwt_helper.rb
module GsptcgvwtHelper
end

app/helpers/gsptcvwt_helper.rb
module GsptcvwtHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ilsimage_helper.rb
module IlsimageHelper
end

app/helpers/ilsvwt_helper.rb
module IlsvwtHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/sptcimage_helper.rb
module SptcimageHelper
end

app/helpers/sptcvwt_helper.rb
module SptcvwtHelper
end

app/helpers/sptgcvwt_helper.rb
module SptgcvwtHelper
end

app/helpers/usertype_helper.rb
module UsertypeHelper
end

app/helpers/vcrtemp_helper.rb
module VcrtempHelper
end

app/views/shared/_btmCustNavContainer.html.erb
<div id="custBotmDiv">
   <nav class="navBottom" >
   <ul>
<%= render :partial => 'shared/topRowBtmNav' %>
<%= render :partial => 'shared/secondRowBtmNav' %>
<%= render :partial => 'shared/iconRowBtmNav' %>
   </ul>
   </nav>
<%= render :partial => 'shared/legalFooter' %>
   </div>

app/views/shared/_btmHomeCustNavContainer.html.erb
<div id="custBotDivHomePage">
   <nav class="navBottom" >
   <ul>
<%= render :partial => 'shared/topRowBtmNav' %>
<%= render :partial => 'shared/secondRowBtmNav' %>
<%= render :partial => 'shared/iconRowBtmNav' %>
   </ul>
   </nav>
<%= render :partial => 'shared/legalFooter' %>
   </div>

app/views/shared/_head.html.erb
<head>
<meta charset="UTF-8"> 
<title>Stuff</title>


<link rel="stylesheet" type="text/css" media="screen and (max-width: 5000px) and (min-width: 481px)" href="css/application.css"> 
<link rel="stylesheet" type="text/css" media="screen and (max-width: 480px) and (min-width: 0px)" href="css/mystyle480and0.css"> 
<%= stylesheet_link_tag 'emregistry', 'http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' %>
<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" %>
<%= javascript_include_tag "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js" %>
</head>

app/views/shared/_iconRowBtmNav.html.erb
<li class="navSiteMapList">
   <a href="#" class="styleMySiteMapIcons"><%= image_tag "linkedInPlaceHolder50x50.png", :class => "styleMySiteMapIcons" %></a>
   <a href="#" class="styleMySiteMapIcons"><%= image_tag "facebookPlaceHolder50x50.png", :class => "styleMySiteMapIcons"  %></a>
   <a href="https://twitter.com/mdbeckley_rails" class="styleMySiteMapIcons"><%= image_tag "twitterPlaceHolder50x50.png", :class =>  "styleMySiteMapIcons" %></a>
   <a href="#" class="styleMySiteMapIcons"><%= image_tag "instaPlaceHolder50x50.png", :class => "styleMySiteMapIcons"  %></a>
   <a href="#" class="styleMySiteMapIcons"><%= image_tag "googlePlusPlaceHolder50x50.png", :class => "styleMySiteMapIcons"  %></a>
</li>

app/views/shared/_insertDeviseStuff.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_legalFooter.html.erb
<div id="footer">
   <footer>Legal copyright requirements here! Copyright Emregistry 2015&copy;</footer>
</div>

app/views/shared/_secondRowBtmNav.html.erb
<li class="navSiteMapList">
   <b class="admin">Admin only row</b>
   |<%= link_to "Play Ground", playground_path, :class => 'styleMySiteMapLinks' %>
   |<%= link_to " Website Issues", problems_path, :class => 'styleMySiteMapLinks' %>
   |<a href="#" class="styleMySiteMapLinks"> Graphics </a>
   |<%= link_to "Business Plan", businessplan_path, :class => 'styleMySiteMapLinks' %>
   |
</li>

app/views/shared/_topNavBar.html.erb
<nav class="nav"> <!-- think of this as a div tag -->
   
   <ul class="navList">
     <li class="navItem">
    <%= image_tag "emregistry242x40.png", :class => "navItem" %>    
	  <!-- Unhappy with image background color -->
	 <%= link_to "Home", root_path, :class => "colorMenuLinkText", :id => "a"  %>
	 <a href="#" class="colorMenuLinkText" id="b"> Settings </a>
	 <%= link_to "Interact", interacttemp_path, :class => "colorMenuLinkText", :id => "c" %>
     <!--<a href="interact.html" class="colorMenuLinkText" id="c"> Interact </a> -->
     <a href="#" class="colorMenuLinkText" id="d"> Tools </a>
     <a href="contact.html" class="colorMenuLinkText" id="e"> Contact </a>
	 <a href="#" class="colorMenuLinkText" id="f"> Sign-In </a>
	 <%= image_tag "envelopeIcon.png", :class => "navItem", :id => "g" %> 
	 <%= image_tag "userIconZoe.png", :class => "navItem", :id => "j" %> 
    
	 
	 
	 </li>
  </ul>   
</nav>

app/views/shared/_topRowBtmNav.html.erb
<li class="navSiteMapList">
   |<%= link_to " Home", root_path, :class => "styleMySiteMapLinks" %>
   |<a href="#" class="styleMySiteMapLinks"> Start a listing </a>
   |<a href="#" class="styleMySiteMapLinks"> Contact Us </a>
   |<a href="#" class="styleMySiteMapLinks"> Be a Service Provider </a><!--Cont next line -->
   |<a href="#" class="styleMySiteMapLinks"> Legal </a>
   |<a href="#" class="styleMySiteMapLinks"> Advertise with Us </a>
   |<a href="#" class="styleMySiteMapLinks"> Be a Consumer </a>
   |<a href="#" class="styleMySiteMapLinks"> Calculators and Tools </a>|
   </li>